version: '3.7'

services:
    backend:
      container_name: backend
      build:
        context: ./simple-api-student
      networks:
        - my-network
      depends_on:
        - database
      environments:
        - URL=database:5432
        - USERNAME=usr
        - PASSWORD=pwd
        - DB=db

    database:
      container_name: database
      build:
        context: ./db
      volumes:
        - db:/var/lib/postgresql/data
      networks:
        - my-network
      environments:
        - POSTGRES_DB=db
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd

    httpd:
      container_name: frontend
      build:
        context: ./web
      ports:
        - '80:80'
      networks:
        - my-network
      depends_on:
        - backend

networks:
    my-network:

volumes:
  db: