version: '3.7'

services:
    backend:
      container_name: backend
      build:
        context: ./simple-api-student
        dockerfile: java.dockerfile
      networks:
        - my-network
      depends_on:
        - database

    database:
      container_name: database
      build:
        context: ./db
        dockerfile: db.dockerfile
      volumes:
        - db:/var/lib/postgresql/data
      networks:
        - my-network

    httpd:
      container_name: frontend
      build:
        context: ./web
        dockerfile: front.dockerfile
      ports:
        - '80:80'
      networks:
        - my-network
      depends_on:
        - backend

networks:
    my-network:

volumes:
  db: